version: '3'
services:
  rayqueue:
    image: ocordes/rayqueue:latest
    restart: always
    networks:
      - web
    expose:
      - "5000"
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:rayqueue.amac171.astro.uni-bonn.de"
      - "traefik.port=5000"
      - "traefik.protocol=http"
    #ports:
    #  - "5000:5000"
    volumes:
      - rayqueue_data:/home/rayqueue/src/data
    environment:
      MAIL_SERVER: exim-relay
      MAIL_PORT: 8025

networks:
  web:
    external: true


volumes:
  rayqueue_data:
