"""add Image and QueueElement definitions

Revision ID: 1b7cac9bf066
Revises: a1e197611697
Create Date: 2019-03-06 18:36:08.869065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b7cac9bf066'
down_revision = 'a1e197611697'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('finished', sa.DateTime(), nullable=True),
    sa.Column('state', sa.Integer(), nullable=True),
    sa.Column('model', sa.Integer(), nullable=True),
    sa.Column('render_image', sa.Integer(), nullable=True),
    sa.Column('log_file', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_image_created'), 'image', ['created'], unique=False)
    op.create_index(op.f('ix_image_finished'), 'image', ['finished'], unique=False)
    op.create_table('queue_element',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.Column('worker_id', sa.Integer(), nullable=True),
    sa.Column('state', sa.Integer(), nullable=True),
    sa.Column('requested', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['image.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_queue_element_requested'), 'queue_element', ['requested'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_queue_element_requested'), table_name='queue_element')
    op.drop_table('queue_element')
    op.drop_index(op.f('ix_image_finished'), table_name='image')
    op.drop_index(op.f('ix_image_created'), table_name='image')
    op.drop_table('image')
    # ### end Alembic commands ###
