"""users status flags

Revision ID: 3558e3438373
Revises: d05bb47284b7
Create Date: 2019-01-29 14:46:50.468347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3558e3438373'
down_revision = 'd05bb47284b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('administrator', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('email_verified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'email_verified')
    op.drop_column('user', 'administrator')
    # ### end Alembic commands ###
