"""add activity table

Revision ID: 3cc4163bc4c5
Revises: 5a16fa81ede2
Create Date: 2019-04-13 16:23:16.284722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cc4163bc4c5'
down_revision = '5a16fa81ede2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('day_activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('stat_total_images', sa.Integer(), nullable=True),
    sa.Column('stat_total_errors', sa.Integer(), nullable=True),
    sa.Column('stat_total_submits', sa.Integer(), nullable=True),
    sa.Column('stat_render_time', sa.Interval(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('day_activity')
    # ### end Alembic commands ###
