"""add project_images to projects

Revision ID: 49786136c3b0
Revises: 72324d818f1f
Create Date: 2019-04-21 13:17:03.475871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49786136c3b0'
down_revision = '72324d818f1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('project_images', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'project_images')
    # ### end Alembic commands ###
