"""add time requested to image

Revision ID: 5a16fa81ede2
Revises: 7af66d100711
Create Date: 2019-04-07 13:31:56.351217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a16fa81ede2'
down_revision = '7af66d100711'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('requested', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_image_requested'), 'image', ['requested'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_image_requested'), table_name='image')
    op.drop_column('image', 'requested')
    # ### end Alembic commands ###
