"""add icon name to file

Revision ID: 74d179845630
Revises: 802488a70265
Create Date: 2019-03-23 18:42:36.470346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74d179845630'
down_revision = '802488a70265'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('icon_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file', 'icon_name')
    # ### end Alembic commands ###
