"""add project_time to project

Revision ID: 7af66d100711
Revises: 8035b2af0b71
Create Date: 2019-04-07 13:27:03.706531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7af66d100711'
down_revision = '8035b2af0b71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('project_time', sa.Interval(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'project_time')
    # ### end Alembic commands ###
