"""add version to project

Revision ID: 7bb2046dfd07
Revises: fe36d17683e3
Create Date: 2019-02-20 08:39:06.431508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bb2046dfd07'
down_revision = 'fe36d17683e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('version', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'version')
    # ### end Alembic commands ###
