"""add project type

Revision ID: 99e0a1b981e8
Revises: ce72f4279ab8
Create Date: 2019-02-05 19:16:07.213226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99e0a1b981e8'
down_revision = 'ce72f4279ab8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('project_type', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'project_type')
    # ### end Alembic commands ###
