"""add hostinfo table

Revision ID: e58f689bc899
Revises: 49786136c3b0
Create Date: 2019-05-03 18:40:39.748428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e58f689bc899'
down_revision = '49786136c3b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('host_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(), nullable=True),
    sa.Column('hostname', sa.String(), nullable=True),
    sa.Column('cpus', sa.Integer(), nullable=True),
    sa.Column('mem', sa.String(), nullable=True),
    sa.Column('os', sa.String(), nullable=True),
    sa.Column('python', sa.String(), nullable=True),
    sa.Column('active', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_host_info_active'), 'host_info', ['active'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_host_info_active'), table_name='host_info')
    op.drop_table('host_info')
    # ### end Alembic commands ###
