swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger REST Article
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/api"

# Paths supported by the server application
paths:
  /login:
    post:
      operationId: "app.api.users.login"
      tags:
        - "Login"
      summary: "Login procedure"
      description: "Login procedure"
      parameters:
        - name: "user"
          in: "body"
          description: "Login User"
          required: True
          schema:
            type: object
            properties:
              username:
                type: string
                description: "Username"
              password:
                type: string
                description: "Password"
      responses:
        201:
          description: "Successfully logged in"

  /users:
    get:
      operationId: "app.api.users.read"
      tags:
        - "Users"
      summary: "The user data structure supported by the server application"
      description: "Read the list of users"
      responses:
        200:
          description: "Successful read user list operation"
          schema:
            type: "array"
            items:
              properties:
                username:
                  type: "string"
                first_name:
                  type: "string"
                last_name:
                  type: "string"
                timestamp:
                  type: "string"
